import { useEffect, useState } from "react";
import { createEvaluationRun, evaluationReportUrl, getEvaluationRuns } from "../api";

const baselineCases = [
  { question: "What is the main goal of RAGLens?", expected_document: "raglens-demo.md" },
  { question: "What does a persisted RAG trace capture?", expected_document: "raglens-demo.md" },
];

export default function Evaluations() {
  const [runs, setRuns] = useState([]); const [selected, setSelected] = useState(null); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function load() { try { const next = await getEvaluationRuns(); setRuns(next); setSelected(current => current || next[0] || null); } catch (err) { setError(err.message); } }
  useEffect(() => { load(); }, []);
  async function runBaseline() { setBusy(true); setError(""); try { const run = await createEvaluationRun({ name: `Local baseline ${new Date().toLocaleString()}`, cases: baselineCases, top_k: 5, chunk_size: 900 }); setRuns(current => [run, ...current]); setSelected(run); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  return <section className="py-12"><p className="eyebrow">Quality evaluation</p><div className="mt-3 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold">Evaluation runs</h1><p className="mt-2 text-slate-400">Run labeled questions, compare metrics, and inspect failures.</p></div><button className="action-primary" disabled={busy} onClick={runBaseline}>{busy ? "Running evaluation…" : "Run local baseline"}</button></div>{error && <p className="mt-5 rounded-lg bg-rose-950/40 p-3 text-sm text-rose-200">{error}</p>}{selected && <><div className="mt-8 grid gap-3 sm:grid-cols-4">{Object.entries(selected.averages).map(([key, value]) => <div key={key} className="panel p-4"><p className="text-xs capitalize text-slate-500">{key.replace("_", " ")}</p><p className="mt-2 text-2xl font-bold text-cyan-300">{(value * 100).toFixed(0)}%</p></div>)}</div><div className="mt-6 flex gap-3"><a className="action-secondary" href={evaluationReportUrl(selected.id, "md")}>Export Markdown</a><a className="action-secondary" href={evaluationReportUrl(selected.id, "pdf")}>Export PDF</a></div><div className="panel mt-6"><div className="border-b border-slate-800 p-5"><p className="font-semibold">Configuration snapshot</p><p className="mt-1 text-sm text-slate-400">{selected.config.provider} · {selected.config.retrieval} · top_k {selected.config.top_k} · indexed chunk size {selected.config.chunk_size}</p></div>{selected.results.map(result => <div key={result.question} className="border-b border-slate-800 p-5 last:border-0"><div className="flex justify-between gap-3"><p className="font-medium">{result.question}</p><span className={result.retrieval_hit ? "text-emerald-400 text-sm" : "text-amber-300 text-sm"}>{result.retrieval_hit ? "Expected source retrieved" : "Review retrieval"}</span></div><p className="mt-2 text-sm text-slate-400">Faithfulness {(result.scores.faithfulness * 100).toFixed(0)}% · Citation support {(result.scores.citation_support * 100).toFixed(0)}% · {result.total_ms}ms</p><p className="mt-3 text-sm text-slate-300">{result.answer}</p></div>)}</div></>}<div className="mt-8 grid gap-3">{runs.map(run => <button key={run.id} onClick={() => setSelected(run)} className="panel flex justify-between p-4 text-left"><span>{run.name}</span><span className="text-sm text-slate-400">Faithfulness {(run.averages.faithfulness * 100).toFixed(0)}%</span></button>)}</div></section>;
}
